---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes
- name: restart php{{ BPHP_VERSION }}-fpm
  service: name=php{{ BPHP_VERSION }}-fpm state=restarted enabled=yes
- name: restart mysql
  service: name=mysql state=restarted enabled=yes
- name: restart memcached
  service: name=memcached state=restarted enabled=yes
