---
- name: "configure server and basic install"
  hosts: all
  roles:
    - user
    - timezone
    - setup
- name: "install frontend"
  hosts: bestdeals2-frontend
  roles:
    - frontend
    - cron
- name: "install backend"
  hosts: bestdeals2-backend
  roles:
    - backend
  tags:
    - backend
