---
- name: add cronjob to frontend
  cron:
    name: "blockip"
    minute: "*/10"
    job: "/usr/bin/python /etc/nginx/blockip/blockip.py >/dev/null 2>&1"
  when: ansible_hostname=="bestdeals2-frontend" or ansible_hostname=="bestdeals2-frontendv1"
