---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes
- name: restart php{{ FPHP_VERSION }}-fpm
  service: name=php7.3-fpm state=restarted enabled=yes
- name: restart memcached
  service: name=memcached state=restarted enabled=yes